### ISSUE TITLE
[V2.0.0] `"setuptools>=75.6"` and `"tzdata>=2020.5"`?

### ISSUE THREAD

**Issue by kseistrup** [Rory-Sullivan/metno-locationforecast#10]
I am packaging `metno-locationforecast` for [AUR](https://aur.archlinux.org/packages/python-metno-locationforecast) and have a couple of questions about dependencies:

1. Apparently, `"setuptools>=75.6"` is required now. Is that a hard requirement? ArchLinux, that is otherwise known as a bleeding edge distribution, only sports v75.2 (released only 5 weeks ago), so building the package from source fails unless I patch `pyproject.toml` (in which case it seems to build without any problems).
2. `"tzdata>=2020.5"` is listed as a dependency, but nowhere in the source is `tzdata` imported, as far as I can tell?

Cheers.

**Comment by Rory-Sullivan** [comment]
Hi, thank you for that.

1. `setuptools` is only required for building the package and not for running it (in case that's not obvious). v75.6 is what I used to build it, and I haven't validated the build with anything else, but if v75.2 is working for you I'm sure that's fine.
2. `tzdata` is not called directly by my code but it is used by the [zoneinfo](https://docs.python.org/3/library/zoneinfo.html) module, which is used by my code. From my understanding of the documentation `tzdata` is used as a fallback if the operating system does not have a built in time zone database. In my case on Windows 11 it is necessary to install `tzdata` else the package will fail, this may not be the case on all operating systems, but I have included it as a dependency to make sure the package works in all cases.

Let me know if you have any more questions on this.

**Comment by kseistrup** [comment]
Thanks for the clarification. I will have to patch the `pyproject.toml` file then, in order to build the package for ArchLinux. That's alright. However, should other distros decide to package this module, they will run into the same problems.

----

This is just a continuation of the points above, in case other Linux users (or packagers) see this issue:

1. Yes, `setuptools` is required for building the package. I should have been more specific: `setuptools` is in the `makedepends=()` array of the package build instructions (not the `depends=()` array). Building fails because `pyproject.toml` require the all new v75.6, while ArchLinux is still at v75.2 (which is only one month old). Therefore I need to patch the project file to require v75.2 (or earlier).
2. The `tzdata` package is a part of ArchLinux/core (and presumable also other Linux distros' equivalent of “core”). It's not an error of me to hold the `tzdata` package a requirement for `metno-locationforecast`, but it is an unnecessary redundancy, and a package linter will warn about this unnecessary requirement (which is why I landed here in the first place). Since I already have to patch the project file for the `setuptools` version, I will just patch out the `tzdata` requirement and the linter will be happy.

:smiley_cat:
