### ISSUE TITLE
Apply ‘.expanduser()’ to user provided paths

### ISSUE THREAD

**Issue by kseistrup** [Rory-Sullivan/metno-locationforecast#3]
It would be convenient if `.expanduser()` were invoked on `pathlib.Path` objects, so that references to `$HOME` could be given with just `~`:

```py
>>> os.environ['HOME']
'/home/kseistrup'
>>> pathlib.Path('~/data').resolve()
PosixPath('/home/kseistrup/~/data')
>>> pathlib.Path('~/data').expanduser().resolve()
PosixPath('/home/kseistrup/data')
```

As far as I can see, this is only necessary in `config.py` — all other places use `.resolve()`'ed paths from `config.py`.

```diff
diff --git a/metno_locationforecast/config.py b/metno_locationforecast/config.py
index 901a4d3..10bc86b 100644
--- a/metno_locationforecast/config.py
+++ b/metno_locationforecast/config.py
@@ -60,11 +60,11 @@ class Config:
         for file in self.possible_user_config_files:
 
             config_parser = ConfigParser()
-            config_parser.read(file.resolve())
+            config_parser.read(file.expanduser().resolve())
 
             if self.section_header in config_parser:
                 user_config = dict(config_parser[self.section_header])
-                self.user_config_file = str(file.resolve())
+                self.user_config_file = str(file.expanduser().resolve())
                 break
 
         return user_config
```

:paperclip: [config-py-diff.txt](https://github.com/Rory-Sullivan/metno-locationforecast/files/7357140/config-py-diff.txt)

**Comment by Rory-Sullivan** [comment]
This makes a lot of sense. I will implement this in dues course.

**Comment by Rory-Sullivan** [comment]
This functionality has been added in [v1.1.0](https://github.com/Rory-Sullivan/metno-locationforecast/releases/tag/v1.1.0), now available from [PyPI](https://pypi.org/project/metno-locationforecast/).
