### ISSUE TITLE
Setting install_requires for requests to "requests>=2.20.0"

### ISSUE THREAD

**Issue by Amir-101** [Rory-Sullivan/metno-locationforecast#5]
Hi,

I have compatibility issues when importing the package in a pre-defined environment. It could save me some work if the argument install_requires was switched to "requests>=2.20.0" instead of  "requests~=2.20.0" in the setup.py file. requests is already set to  "requests>=2.20.0" in the pipfile but the install_recquires seem to be prevalent.

**Comment by Rory-Sullivan** [comment]
Thanks for pointing this out, I have made this change in [v1.1.0](https://github.com/Rory-Sullivan/metno-locationforecast/releases/tag/v1.1.0), which is available on [PyPI](https://pypi.org/project/metno-locationforecast/).
