### ISSUE TITLE
[Enhancement] Import `niquests` as `requests`

### ISSUE THREAD

**Issue by kseistrup** [Rory-Sullivan/metno-locationforecast#6]
`niquest` is a modern drop-in replacement for `requests`:

* https://github.com/jawah/niquests

The `metno_locationforecast` module could try and `import niquests as requests`, in order to transparently use `niquests` if available.

E.g.:

```diff
diff --git a/metno_locationforecast/forecast.py b/metno_locationforecast/forecast.py
index 8eb68fe..5425463 100644
--- a/metno_locationforecast/forecast.py
+++ b/metno_locationforecast/forecast.py
@@ -10,7 +10,10 @@ import json
 from pathlib import Path
 from typing import Optional, Dict, Union
 
-import requests
+try:
+    import niquests as requests
+except ImportError:  # Also covers the subclassed ModuleNotFoundError
+    import requests
 
 from .config import Config
 from .data_containers import Interval, Place, Variable, Data
```

**Comment by Rory-Sullivan** [comment]
Hi @kseistrup, sorry for the slow response on this I don't have mush time for personal projects at the moment. Have you tried the above change and has it worked for you?

**Comment by kseistrup** [comment]
@Rory-Sullivan, I've been using a patched version of this repo (+ patched versions of other apps that use `python-requests`) since I posted thios issue, and I have had exactly zero problems or inaccuracies.

**Comment by kseistrup** [comment]
I will call off this issue. The `niquests` module (or one of its dependencies) are now lowercasing all header keys — something that makes sense, since headers are case-insensitive — which breaks `metno-locationforecast` because the latter looks for the cased dictionary keys `Last-Modified` and `Expires` (in `forecast.py`).

I may or may not return with a pull-request one day.

**Comment by Rory-Sullivan** [comment]
Thanks for closing this off, though it does sound like the library shouldn't be looking for cased version of those headers. Something I will have a look into.

**Comment by kseistrup** [comment]
Well, `forecast.py` has e.g.:

```py
   178	            self.json["headers"] = dict(self.response.headers)
```

and later e.g.:

```py
   200	        last_modified = dt.datetime.strptime(json["headers"]["Last-Modified"], HTTP_DATETIME_FORMAT)
```

So when `niquests` lowercases all headers keys, everything goes boom. :bomb: 

These headers are from `metno-locationforecast`:

```json
{
  "Server": "nginx/1.18.0 (Ubuntu)",
  "Date": "Wed, 03 Jul 2024 18:40:03 GMT",
  "Content-Type": "application/json",
  "Content-Length": "456",
  "Connection": "keep-alive",
  "Expires": "Wed, 03 Jul 2024 18:43:03 GMT",
  "Last-Modified": "Wed, 03 Jul 2024 18:40:03 GMT",
  "X-Backend-Host": "b_157_249_79_118",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET",
  "Access-Control-Allow-Headers": "Origin",
  "Content-Encoding": "gzip",
  "Vary": "Accept, Accept-Encoding",
  "X-Varnish": "510673503",
  "Age": "0",
  "Via": "1.1 dalton-a (Varnish/7.2)",
  "Accept-Ranges": "bytes"
}
```

**Comment by stucka** [comment]
Very belated update, if I may? I was searching and found this thread.

Both requests and niquests have a structures.CaseInsensitiveDict that would be useful in this exact use case. It doesn't solve the problem of niquests breaking things, but it gives a more sensible way to handle the dictionary.

from niquests.structures import CaseInsensitiveDict

headers = CaseInsensitiveDict()

headers['last-modified'] = "testdatahere"

print(headers['Last-Modified'])

**Comment by kseistrup** [comment]
@stucka, thanks for the belated update. :pray:

I haven't looked into this for a long time, instead I've just avoided `import niquests as requests` where I knew it would give me troubles. I haven't followed the inner changes of niquests, but when I make a nowcast now, with niquests as requests, the resulting JSON now has its keys lowercased _except_ for the headers. E.g.:

**.headers**:

```json
{
  "Server": "nginx/1.18.0 (Ubuntu)",
  "Date": "Fri, 03 Jul 2026 07:57:51 GMT",
  "Content-Type": "application/json",
  "Content-Length": "483",
  "Connection": "keep-alive",
  "Last-Modified": "Fri, 03 Jul 2026 07:57:51 GMT",
  "Expires": "Fri, 03 Jul 2026 08:00:51 GMT",
  "X-Backend-Host": "b_157_249_79_168",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET",
  "Access-Control-Allow-Headers": "Origin",
  "Content-Encoding": "gzip",
  "Vary": "Accept, Accept-Encoding",
  "X-Varnish": "14812130495",
  "Age": "0",
  "Via": "1.1 dalton-a (Varnish/7.7)",
  "Accept-Ranges": "bytes"
}
```

**.data.properties.meta**:

```json
{
  "updated_at": "2026-07-03T07:57:49Z",
  "units": {
    "air_temperature": "celsius",
    "precipitation_amount": "mm",
    "precipitation_rate": "mm/h",
    "relative_humidity": "%",
    "ultraviolet_index_clear_sky": "1",
    "wind_from_direction": "degrees",
    "wind_speed": "m/s",
    "wind_speed_of_gust": "m/s"
  },
  "radar_coverage": "ok"
}
```

So perhaps niquests has made some changes.
